[project]
name = "canary"
version = "0.1.0"
description = "CANary is the CAN-Bus Simulator for Raspberry Pi and Web"
authors = ["Your Organization <email@example.com>"]
channels = ["conda-forge"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/yourusername/canary"

[tasks]
test = "pytest tests/"
lint = "ruff check src/"
format = "ruff format src/"
start = "python -m canary.cli"

[dependencies]
python = ">=3.10,<3.13"
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
ruff = ">=0.0.272"
typer = ">=0.9.0"
pydantic = ">=2.0.0"
rich = ">=13.0.0"
loguru = ">=0.7.0"
