@startuml C01-20_ContextDiagram
actor User
node "TF-Canary Application" {
  component MainWindow
  component CANManager
  component ScenarioManager
  component CarSimulator
  component CLI
  component LoggingSystem
}
database "SQLiteDB"
actor CANHardware
actor VirtualCAN

User --> MainWindow : interact
User --> CLI : execute commands
MainWindow --> ScenarioManager : select scenario
ScenarioManager --> SQLiteDB : load scenario
ScenarioManager --> CANManager : trigger CAN data
CANManager --> CarSimulator : inputs
CarSimulator --> CANManager : outputs
CANManager --> CANHardware : hardware interface
CANManager --> VirtualCAN : virtual interface
CANManager --> LoggingSystem : log activities